---
engines:
  gofmt:
    enabled: true

  golint:
    enabled: true

  govet:
    enabled: true

  shellcheck:
    enabled: true

  fixme:
    enabled: true

ratings:
  paths:
    - "**.go"
    - "**.sh"

exclude_paths:
  - vendor/

  # generated files
  - rpc/pb/root.pb.go
  - rpc/pb/root.pb.gw.go
